services:
  - type: web
    name: comic-downloader-backend
    runtime: node
    rootDir: backend
    build:
      buildCommand: npm install
      publishDir: .
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/go/src/github.com/AfroPK/comic-downloader-web/backend/node_modules/.cache/puppeteer
    healthCheck:
      path: /api/health
